### PR TITLE
Setup main.handlebars

### PR DESCRIPTION
**Pull request by jwolfcrafter**
Layout that should be used in all future pages

### CODE REVIEW

**Comment by mpolimen** [comment]
{{{title}}} should be {{title}} because it's data not html that needs rendering. Also, we don't care about having an <h1> at the start of each page necessarily, given the figma design (the landing page comes to mind). I also wouldn't care for our names being at the bottom of every single page (maybe it'd be fine for the landing page)

**Comment by mpolimen** [comment]
I'm sorry if I just didn't notice this the first time, but the nav bar with those elements will not be on every page. For instance, log-in and sign-up are only on the landing page, and the profile pic is only on all other pages.  My bad for not being thorough. If you want to be able to do a nav bar in the main handlebars, you could do an if statement that takes in some boolean (like isLanding) that will display the landing nav bar if true, or the other nav if false.

**Comment by mpolimen** [comment]
Also, why pass in a log_in_class / sign_in_class, there's no need for them to be variable, is there? Just give it a static name that we'll use in the CSS.

**Comment by roccopolimen** [comment]
don't forget to add the lang="en" so the validator doesn't warn on that.

I also have reservations about using classes for the log in and signup like that. I feel like that would all get handled by client side javascript whether to show or hide that stuff.

Same applies to profile, if they aren't logged in, then we should be hiding the profile button since, well, they don't have a profile to go to.

I would suggest default being to show the log-in/signup links and to set the profile link to hidden, and then in client side js, if they are logged in, to do a switcheroo.

The implementation of the footer is fine.

**Pull request merged**
