### PR TITLE
Board html

### PR DESCRIPTION
**Pull request by roccopolimen**
finished the board html. In terms of style and word choice, we can always change later, focus more on the structure. 

Also realized I never had a functionality for adding a list to the board so that was added to the routes and tested lightly.

### CODE REVIEW

**Comment by roccopolimen** [comment]
This is already changed a lot, don't bother looking at it for now. I'll recommit when I make changes with the CSS and push them together.

**Comment by mpolimen** [comment]
Very handsome pull request; no complaints

**Comment by ryan280** [comment]
This looks really good, I couldn't find a way to remove the inline styling.

**Comment by bwormser** [comment]
Very Beautiful

**Pull request merged**
